const express = require('express');
const supabase = require('../db/supabase');
const { estimateRoute } = require('../services/fare');
const { makeReference } = require('../services/reference');
const { sendBookingConfirmation } = require('../services/sms');

const router = express.Router();

// POST /api/bookings — create a confirmed booking
router.post('/', async (req, res) => {
  const {
    pickup, dropoff, scheduledAt, paymentMethod,
    rider, source = 'form',
  } = req.body || {};

  if (!pickup?.address || !dropoff?.address || !scheduledAt || !paymentMethod) {
    return res.status(400).json({ error: 'Missing pickup, dropoff, time, or payment method.' });
  }
  if (!rider?.name || !rider?.phone) {
    return res.status(400).json({ error: 'Name and phone are required.' });
  }
  if (!['card', 'cash'].includes(paymentMethod)) {
    return res.status(400).json({ error: 'Payment method must be card or cash.' });
  }

  // Priced against the real route where routing is enabled, and against
  // the scheduled hour rather than right now — a 5pm airport run should
  // not be quoted on 11am traffic. Falls back to the straight-line
  // estimate automatically if routing is off or unavailable.
  const quote = await estimateRoute(pickup, dropoff, scheduledAt);
  const { distanceMiles, durationMinutes, fare, polyline, source: routeSource } = quote;

  try {
    // Generate a unique reference (retry a couple of times on the rare collision).
    let reference = makeReference();
    for (let attempt = 0; attempt < 3; attempt++) {
      const { data: existing, error: checkErr } = await supabase
        .from('bookings')
        .select('reference')
        .eq('reference', reference)
        .maybeSingle();
      if (checkErr) throw checkErr;
      if (!existing) break;
      reference = makeReference();
    }

    const { data, error } = await supabase
      .from('bookings')
      .insert({
        reference,
        pickup_address: pickup.address,
        pickup_lat: pickup.lat ?? null,
        pickup_lng: pickup.lng ?? null,
        dropoff_address: dropoff.address,
        dropoff_lat: dropoff.lat ?? null,
        dropoff_lng: dropoff.lng ?? null,
        scheduled_at: scheduledAt,
        distance_miles: distanceMiles,
        duration_minutes: durationMinutes,
        fare,
        payment_method: paymentMethod,
        rider_name: rider.name,
        rider_phone: rider.phone,
        rider_email: rider.email ?? null,
        source,
        // Cached at creation so no map render ever needs to re-bill a
        // routing request. Null when routing is disabled — the map then
        // draws a straight connector instead of road geometry.
        route_polyline: polyline ?? null,
        route_source: routeSource === 'google' ? 'google' : 'haversine',
        // track_token is intentionally NOT set here. It takes its column
        // default, encode(gen_random_bytes(16),'hex'), so the secret is
        // generated by Postgres with a CSPRNG rather than by application
        // code — one less place for a weak Math.random() to creep in.
      })
      .select()
      .single();

    if (error) throw error;

    // Best-effort booking confirmation text — never let an SMS hiccup turn a
    // successful save into a 500 that makes the rider re-book.
    sendBookingConfirmation(data).catch((e) =>
      console.warn('[bookings] confirmation SMS failed (non-fatal):', e.message));

    // The tracking URL is assembled here rather than in the browser so
    // the same string can be dropped straight into the confirmation SMS
    // or email when that lands, without the token ever being rebuilt
    // (and potentially malformed) in two places.
    const base = process.env.PUBLIC_APP_URL || '';
    res.status(201).json({
      ...data,
      trackUrl: base ? `${base}/track/${data.track_token}` : `/track/${data.track_token}`,
    });
  } catch (err) {
    console.error('booking insert error', err.message);
    res.status(500).json({ error: 'Could not create booking.' });
  }
});

// GET /api/bookings/:reference — fetch a booking (confirmation screen / lookup)
//
// SECURITY NOTE — pre-existing, flagged not silently changed:
// This returns the full row, including rider_phone and rider_email, to
// anyone who presents a valid reference. A reference is 5 characters
// from a 32-symbol alphabet (~33.5M combinations), which is small enough
// to enumerate with a script. Fixing it properly means either narrowing
// this projection or requiring the phone number as a second factor, and
// both change the contract the confirmation screen depends on — so it is
// left alone here and called out in MAPS_IMPLEMENTATION.md instead.
//
// The new rider tracking flow deliberately does NOT go through this
// endpoint. GET /api/track/:token uses a 128-bit token and returns a
// narrow, PII-free projection precisely so the public tracking link does
// not inherit this weakness.
router.get('/:reference', async (req, res) => {
  try {
    const { data, error } = await supabase
      .from('bookings')
      .select('*')
      .eq('reference', req.params.reference)
      .maybeSingle();
    if (error) throw error;
    if (!data) return res.status(404).json({ error: 'Booking not found.' });
    res.json(data);
  } catch (err) {
    console.error('booking fetch error', err.message);
    res.status(500).json({ error: 'Could not fetch booking.' });
  }
});

module.exports = router;
